### ISSUE TITLE
Handle spaces in working path gracefully

### ISSUE THREAD

**Issue by KaiHa** [blt/port_compiler#21]
It looks like _port_compiler_ chokes on spaces in paths. I have executed `rebar3 compile` in the current directory `~/workspace/CBOX - Dialyzer` and this is what I have found in the debug output:

```
===> Port Cmd: cc -c -m64  -Ic_src -Wall -fPIC  -I"/usr/lib/erlang/lib/erl_interface-3.7.18/include" -I"/usr/lib/erlang/erts-6.2/include"   /var/lib/jenkins/workspace/CBOX - Dialyzer/_build/default/lib/bcrypt/c_src/async_queue.c -o /var/lib/jenkins/workspace/CBOX - Dialyzer/_build/default/lib/bcrypt/c_src/async_queue.o
...
===> cc: error: Dialyzer/_build/default/lib/bcrypt/c_src/async_queue.c: No such file or directory
cc: error: Dialyzer/_build/default/lib/bcrypt/c_src/async_queue.o: No such file or directory
```

**Comment by blt** [comment]
Hmm, this ought to be easy to fix. I'm on the last day of a vacation but I'll try to tackle this on the plane trip back. 

Thanks for the report!

**Comment by ghost** [comment]
@KaiHa, I failed to provoke a failure with rebar 2.6.4 and rebar 3.3.1 + pc 1.4.0. Do you have an example project to reproduce the fault?

**Comment by KaiHa** [comment]
Sorry @blt, I have no project at hand and I am currently not working with Erlang.

**Comment by ghost** [comment]
I cannot reproduce it here. @ferd, @tsloughter, is it possible this was a general issue in rebar3 that has since been corrected?

**Comment by tsloughter** [comment]
Resolved by https://github.com/blt/port_compiler/pull/31

**Comment by acautin** [comment]
@tsloughter this issue is still giving problems, after processing the files  using escape_chars the newly added \ is not handled well by the filelib:wildcard function resulting in an empty list and nothing gets compiled.

```
6> filelib:wildcard("/Users/agustin/Documents/with spaces/erlscrypt/c_src/*.cpp").  
["/Users/agustin/Documents/with spaces/erlscrypt/c_src/scrypt.cpp",
 "/Users/agustin/Documents/with spaces/erlscrypt/c_src/scrypt_nif.cpp",
 "/Users/agustin/Documents/with spaces/erlscrypt/c_src/scrypt_port.cpp",
 "/Users/agustin/Documents/with spaces/erlscrypt/c_src/sha256.cpp"]
7> filelib:wildcard("/Users/agustin/Documents/with\\ spaces/erlscrypt/c_src/*.cpp").
[]
```
Maybe I am missing something ?.
